### ISSUE TITLE
How to save the model

### ISSUE THREAD

**Issue by Mega4alik** [haifengl/smile#135]
Hi, I'm new to Smile. 
Could not find information about saving the trained model and then loading it back.
Thanks in advance

**Comment by haifengl** [comment]
in scala, use write.xstream to save any object/model.

**Comment by Mega4alik** [comment]
Thanks for response, What about Java?

**Comment by haifengl** [comment]
Just use XStream. Three lines should be enough. If you have to use Java serialization, we can add the support to clustering and other alorithms.

**Comment by Mega4alik** [comment]
Constantly getting Out of memory error, even after increasing the heap size.
Can you suggest some alternative?

Thanks in advance

**Comment by Mega4alik** [comment]
Tried to print directly to file as well 

 PrintWriter out = new PrintWriter(new File(g.Path+"/temp/model.txt"));        
 xstream.toXML(model, out);

**Comment by haifengl** [comment]
more details on out of memory error? when and where? how big your data/model?

**Comment by haifengl** [comment]
If your model is classification or regression, you can save and load them by "write" and "read" methods in the shell directly.

**Comment by Mega4alik** [comment]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.StringBuffer.toString(StringBuffer.java:671)
	at com.thoughtworks.xstream.io.xml.XmlFriendlyReplacer.escapeName(XmlFriendlyReplacer.java:55)
	at com.thoughtworks.xstream.io.xml.AbstractXmlWriter.escapeXmlName(AbstractXmlWriter.java:36)
	at com.thoughtworks.xstream.io.xml.PrettyPrintWriter.startNode(PrettyPrintWriter.java:73)
	at com.thoughtworks.xstream.io.xml.PrettyPrintWriter.startNode(PrettyPrintWriter.java:86)
	at com.thoughtworks.xstream.io.WriterWrapper.startNode(WriterWrapper.java:22)
	at com.thoughtworks.xstream.io.path.PathTrackingWriter.startNode(PathTrackingWriter.java:30)
	at com.thoughtworks.xstream.io.ExtendedHierarchicalStreamWriterHelper.startNode(ExtendedHierarchicalStreamWriterHelper.java:6)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:51)
	at com.thoughtworks.xstream.converters.collections.ArrayConverter.marshal(ArrayConverter.java:34)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:55)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:50)
	at com.thoughtworks.xstream.annotations.AnnotationReflectionConverter.marshallField(AnnotationReflectionConverter.java:46)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:112)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.visit(AbstractReflectionConverter.java:88)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:117)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:73)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:55)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:50)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:52)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:44)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:55)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:50)
	at com.thoughtworks.xstream.annotations.AnnotationReflectionConverter.marshallField(AnnotationReflectionConverter.java:46)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:112)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.visit(AbstractReflectionConverter.java:88)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:117)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:73)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:55)
------------------------------------------------------------------------

**Comment by Mega4alik** [comment]
I need to load/save in Java

**Comment by haifengl** [comment]
what is your model?

**Comment by Mega4alik** [comment]
SVM

**Comment by haifengl** [comment]
For SVM (or any classification and regression algorithms), you can serialize them by Java serialization. See examples here https://www.tutorialspoint.com/java/java_serialization.htm

**Comment by Mega4alik** [comment]
Exception in thread "main" java.io.NotSerializableException: smile.math.kernel.LinearKernel
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at ml.Classifier.learn(Classifier.java:64)
	at ml.Classifier.<init>(Classifier.java:37)
	at global.Function.<init>(Function.java:45)
	at global.Scripts.<init>(Scripts.java:53)
	at global.Scripts.main(Scripts.java:39)

**Comment by Mega4alik** [comment]
static SVM<double[]> model;    
model = new SVM<double[]>(new LinearKernel(), 1.0, Math.max(Y)+1, SVM.Multiclass.ONE_VS_ONE);

**Comment by haifengl** [comment]
The kernel function is not serializable. The fix is pushed to master. Please clone the repo and do "sbt package" to build the libraries locally. See http://haifengl.github.io/smile/index.html#quickstart for details. If everything is okay, I will push a new release soon. Thanks!

**Comment by Mega4alik** [comment]
Thank you, can I build it for Java?

**Comment by haifengl** [comment]
Of course. "sbt package" build everything (most modules are in Java, and only one in Scala)  into jar files. Just copy the jar files to your project.

**Comment by Mega4alik** [comment]
I added smile, smile-core, smile-data, smile-math, smile-ploat jar files into Java project and got this error))

Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at smile.classification.SVM.<clinit>(SVM.java:90)
	at ml.Classifier.learn(Classifier.java:54)
	at ml.Classifier.<init>(Classifier.java:37)
	at global.Function.<init>(Function.java:45)
	at global.Scripts.<init>(Scripts.java:53)
	at global.Scripts.main(Scripts.java:39)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

**Comment by haifengl** [comment]
you need slf4j library.

**Comment by Mega4alik** [comment]
got it, but new error coming up 
Exception in thread "main" java.io.NotSerializableException: smile.classification.SVM$LASVM$SupportVector
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.ArrayList.writeObject(ArrayList.java:762)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.ArrayList.writeObject(ArrayList.java:762)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:988)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at ml.Classifier.learn(Classifier.java:66)
	at ml.Classifier.<init>(Classifier.java:37)
	at global.Function.<init>(Function.java:45)
	at global.Scripts.<init>(Scripts.java:53)
	at global.Scripts.main(Scripts.java:39)

**Comment by haifengl** [comment]
I tried your example yesterday and it works. Probably because it is an empty model (not trained). I updated the inner classes with Serializable and it works with a trained model. Please git pull and try again. Thanks!

**Comment by Mega4alik** [comment]
Thank you. Run "git pull"  and updated all smile libraries in Java project, but still getting the same error.
Here's the code 
static SVM<double[]> model;    

model = new SVM<double[]>(new LinearKernel(), 1.0, Math.max(Y)+1, SVM.Multiclass.ONE_VS_ONE);        
        model.learn(X, Y);                             
        FileOutputStream fileOut = new FileOutputStream(g.Path+"/temp/model.txt");
        ObjectOutputStream out = new ObjectOutputStream(fileOut);
        out.writeObject(model);
        out.close();
        fileOut.close(); 
        model.finish();

**Comment by haifengl** [comment]
It works for me. Did you "sbt package"?

**Comment by haifengl** [comment]
I see. What's your input data type? Sparse array?

**Comment by Mega4alik** [comment]
Actually arrays of integers, but I use double like in examples. Makes no difference for final result. 

double[][] X = gson.fromJson(g.getFileContent(g.Path+"/temp/X.txt"), double[][].class);
int[] Y = gson.fromJson(g.getFileContent(g.Path+"/temp/Y.txt"), int[].class);

**Comment by haifengl** [comment]
Just make smile.math.DoubleArrayList and related classes serializable. Please git pull and build again. Thanks!

**Comment by Mega4alik** [comment]
It worked! 
Thank you and best of luck

**Comment by haifengl** [comment]
version 1.2.2 is released. It may take a couple of days to be available on maven central repo. Thanks!

**Comment by Mega4alik** [comment]
Awesome!

**Comment by naanunaane** [comment]
Hi, I am a beginner to Scala and SMILE. 
I tried using read.xstream("<XML File with my model>"). I get an object of type AnyRef which doesn't allow me to directly use the methods associated with that object (like .predict). I tried passing the AnyRef object as DecisionTree(read.xstream("<XML File with my model>")), but it threw up an error. Very likely a stupid question, but I hope you can help me out! 

Also, I have noticed that a lot of the pages you have mentioned in the comments of the issues here are outdated/unaccessible. 
For ex: your FAQ page.

**Comment by haifengl** [comment]
`model.asInstanceOf[DecisionTree]` does the conversion. The web page is at http://haifengl.github.io now.

**Comment by pdkovacs** [comment]
I am getting
```
java.io.NotSerializableException: java.util.Optional
```
during serialization of a `smile.regression.RandomForest` instance. `RandomForest` has a `Formula` field, which in turn has an `java.util.Optional<Term>` field (`response`). `java.util.Optional` is not serializable indeed.

Any thoughts?

**Comment by pdkovacs** [comment]
Arghhhh, there seems to be more Optional fields in transitive dependencies, such as Variable.measure (also introduced 3 month ago...)...

**Comment by haifengl** [comment]
@pdkovacs I will fix the issue with Optional. It is used in many places in v2.

**Comment by pdkovacs** [comment]
> @pdkovacs I will fix the issue with Optional. It is used in many places in v2.

@haifengl Many thanks for your quick reply and even more thanks for the fix in advance. :-)

In the meantime, I have been trying to use XStream. It successfully serializes and deserializes the `smile.regression.RandomForest` instance successfully. Calling `predict` on the deserialized instance, however, results in this exception:
```
Caused by: java.lang.NullPointerException
	at smile.data.type.StructType.fieldIndex(StructType.java:81)
	at smile.data.formula.Variable.bind(Variable.java:129)
	at smile.data.formula.Formula.lambda$bind$5(Formula.java:219)
	at java.util.Optional.ifPresent(Optional.java:159)
	at smile.data.formula.Formula.bind(Formula.java:219)
	at smile.data.formula.Formula.x(Formula.java:320)
	at smile.regression.RandomForest.predict(RandomForest.java:391)
```
The same code works as expected, if the `smile.regression.RandomForest` instance isn't serialized and deserialized.

**Comment by pdkovacs** [comment]
I am preparing  a pull request here: https://github.com/pdkovacs/forked-smile/commits/model-serialization-regression-i135. The java serialization seems to work OK, but I am stuck at the same issue as with XStream-serialization in my previous comment: the LHS formula field (dependent variable) doesn't seem to be included in the deserialized Variable instance (it's when the LHS formula field's index is queried from the schema at StructType.fieldIndex(StructType.java:81)).

And this issue occurred so far only when I drive the code from my application. SMILE's own RandomForestTest in the SMILE code base doesn't exhibit this problem when augmented with model-de-/serialization: https://github.com/pdkovacs/forked-smile/commit/90d6a4a0e06cae67454e48668309be73c0a84a26#diff-8faad23902535d06f10a6e4eefad794f . The only difference I found so far between how my app is using the api and how the SMILE test is that my app uses DataFrame.union(...) to collect the observations into a single DataFrame:
```
    private final String name;
    private String[] names;
    private DataFrame data;
...
    public void addObservation(double[] explanatories, double dependent) {
        if (this.names == null) {
            this.names = IntStream.range(0, explanatories.length)
                                  .mapToObj(index -> name + index)
                                  .toArray(String[]::new);
        }
        DataFrame newObservation = DataFrame.of(new double[][] { explanatories }, names)
                                            .merge(DoubleVector.of(FORMULA, new double[] { dependent }));
        if (data == null) {
            data = newObservation;
        } else {
            data = data.union(newObservation);
        }
    }
```
The single-row DataFrame instances are created very similarly to how the SMILE's own (and working) RandomForest test does it.
(Again, my app works OK without model (de-)serialization.)

Any ideas how can move ahead with this? Is there anything to fix in my use of the SMILE api? Might the use the DataFrame.union(...) be the culprit?

**Comment by pdkovacs** [comment]
For the benefit of posterity: It turned out that the NPE (which I can observe both with XStream and Java object serialization) goes away if I pass a Tuple instance as parameter to `RegressionTree.predict(Tuple x)` instead of a row of a `DataSet` instance.

**Comment by haifengl** [comment]
@pdkovacs I have removed Optional from all member variables. All models pass the serialization tests. Check it out in master branch.

**Comment by pdkovacs** [comment]
@haifengl Thanks a lot! Modulo some compile errors (#511), it works for me.

**Comment by jodue** [comment]
Hi @haifengl,

i am trying to serialize a RandomForest model via java serialization with smile 2.1.0 but i am running into the following exception:

java.io.NotSerializableException: smile.data.type.ObjectType$$Lambda$305/0x00000007c0bd6040
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
[...]

The issue seems to be that ObjectType.format (i use DoubleType) is a lambda which is not serializable. Do you have any idea how this can be fixed?

Thank you already!

**Comment by haifengl** [comment]
@jovilius ObjectType for double means that you have missing values. But we don’t directly  support missing values in the tree models. I suggest you check your model first. If you don’t have missing values, change the data type to plain double. Then you should be able to serialize the model. I will look into the lambda problem. Thanks

**Comment by jodue** [comment]
Thanks for the insight an the quick response!

I am trying to change to primitive double values but i am running in the following problem:
I have n features (of type double) and 1 class label (which has to be of type int). I am creating the DataFrame from a List of Tuple objects plus the schema. The problem is that the constructor of Tuple takes an array of primitive double which will then lead to an UnsupportedOperationException when the class is extracted (ClassLabels.fit) as the class has to be int. I have the feeling i am not using the API correctly. Can i ask you to point me in the right direction as i was unable to find any documentation on this?

Your help is very much appreciated, thanks!

**Comment by haifengl** [comment]
@jodue show me a few lines of data and your code of importing data. We can fix it quickly.

**Comment by jodue** [comment]
This is the way i did it before changing to primitive double type. I now have the issue that the class label (last index in data array) has to be integer and the rest of the data is double. Is there a better way to create the DataFrame? 

Example data could be simply: [ 1.0, 0.3, 3 ] -> 2 double value features + 1 integer class label

`        List<Tuple> data = new ArrayList<>( vectors.size() );
        List<StructField> fields = new ArrayList<>( allFeatures.size() );
        for ( Feature f : allFeatures )
        {
            fields.add( new StructField( f.getName(), DataTypes.DoubleObjectType ) );
        }
        fields.add( new StructField( RandomForestModel.CLASS_FIELD_NAME, DataTypes.IntegerType ) );
        StructType schema = new StructType( fields );
        for ( FeatureVector vector : vectors )
        {
            Object row[] = vector.toObjectData( allFeatures, true, formatToDouble );
            row[ row.length - 1 ] = vector.getAssignedClass();
            data.add( Tuple.of( row, schema ) );
        }
        
        return DataFrame.of( data );`

**Comment by haifengl** [comment]
Check out http://haifengl.github.io/data.html for some example about `DataFrame`. If your data is of `double[][]`, just do `DataFrame.of(x)`, then drop the third column `data.drop("V3")`, which is in wrong data type. and `data.merge(y)`, where I assume that you have an int vector `y`. It is easier if you separate data and labels firstly.

**Comment by jodue** [comment]
Thank you, i now got it to work the way you proposed. I can serialize/deserialize a model and then use it again. However there seems to be a caveat/strange behavior: If i want to use the deserialized model it (for some reason) needs the "class" property in the tuple which will used for prediction, otherwise an exception is thrown. This is however only the case for the first prediction.

```
	StructType.fieldIndex(String) line: 81	
	Variable.bind(StructType) line: 129	
	Formula.bind(StructType, boolean) line: 219	
	Formula.x(Tuple) line: 320	
	RandomForest.predict(Tuple, double[]) line: 496	
```

```
return index.get(field);
field = "class" --> this property is not part of the tuple which will be used for prediction and is the LHS of the formula in the model
```

I got it to work by adding the "class" property to the prediction-tuple which solves my issue but i still wanted to report this to you as i think that it probably is a bug.

I have one more general question because i did not find any information on it on the webpage: Can smile (ie. for Random Forest Classification) have features of different types? Ie. i wanted to have a mixture of Double, Boolean and String Features but i always got class-cast issues which is why i now convert everything to double. I wonder if using appropriate datatypes for each feature might improve classification performance for RandomForest?! Should this work with smile ATM?

Thank you very much for your help &  i wish you a pleasant day!

**Comment by haifengl** [comment]
@jodue you may not build the model correctly. for working around, you can try a tuple with "class" field (with arbitrary value).

**Comment by ynjacobs** [comment]
Thanks again for this wonderful library!
I have two java files, one with machine learning models and the other with a dataframe to predict the outcome but I keep getting this error:
`Exception in thread "main" java.lang.NullPointerException`
Here is the stack trace:
```
Exception in thread "main" java.lang.NullPointerException
	at smile.data.type.StructType.fieldIndex(StructType.java:81)
	at smile.data.formula.Variable$1.<init>(Variable.java:80)
	at smile.data.formula.Variable.bind(Variable.java:78)
	at smile.data.formula.Formula.lambda$bind$12(Formula.java:253)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at smile.data.formula.Formula.bind(Formula.java:254)
	at smile.classification.DataFrameClassifier.predict(DataFrameClassifier.java:48)
	at Predict.computeTheFile(Predict.java:397)
```

`Predict.java:397` contains `int[] rfpredict = rfr.predict(myDataFrame);`

The model.java file looks like:
```
RandomForest rfr = RandomForest.fit(Formula.lhs("height"), data);
DataFrame predict = dtFrameTest.drop("height",);
int[] rfpredict = rfr.predict(predict);

try {
	 FileOutputStream fileOut =
	 new FileOutputStream("./src/rfrSerialize.ser");
	 ObjectOutputStream out = new ObjectOutputStream(fileOut);
	 out.writeObject(rfr);
	 out.close();
	 fileOut.close();
	 System.out.printf("Serialized data is saved in ./src/rfrSerialize.ser");
	 } catch (IOException i) {
	    i.printStackTrace();
	   }
	}
```

and predict.java looks like:
```
RandomForest rfr;
  	     try {
  	         FileInputStream fileIn = new FileInputStream("./src/rfrSerialize.ser");
  	         ObjectInputStream in = new ObjectInputStream(fileIn);
  	         rfr = (RandomForest) in.readObject();
  	         in.close();
  	         fileIn.close();
  	      } catch (IOException i) {
  	         i.printStackTrace();
  	         return;
  	      } catch (ClassNotFoundException c) {
  	         System.out.println("RandomForest class not found");
  	         c.printStackTrace();
  	         return;
  	      }

  	   int[] rfpredict = rfr.predict(myDataFrame);
  	   System.out.println(rfpredict);
	 }
```
