### ISSUE TITLE
unable to serialize the DecisionTree model using the xstream

### ISSUE THREAD

**Issue by aminaaslam** [haifengl/smile#150]
Hi Hai,
This is my code and i have a Decision Tree model which i am trying to serialize using xstream but it keeps giving this exception.
		XStream xstream = new XStream(new StaxDriver());
		xstream.alias("tree", DecisionTree.class);
		String xml = xstream.toXML(tree);
		System.out.println(xml);

Exception in thread "main" com.thoughtworks.xstream.converters.reflection.ObjectAccessException: Invalid final field smile.classification.DecisionTree$Node.this$0
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.validateFieldAccess(PureJavaReflectionProvider.java:150)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:105)
	at com.thoughtworks.xstream.converters.reflection.ReflectionConverter.marshal(ReflectionConverter.java:44)
	at com.thoughtworks.xstream.core.ReferenceByXPathMarshaller.convertAnother(ReferenceByXPathMarshaller.java:36)
	at com.thoughtworks.xstream.converters.reflection.ReflectionConverter$1.writeField(ReflectionConverter.java:78)
	at com.thoughtworks.xstream.converters.reflection.ReflectionConverter$1.visit(ReflectionConverter.java:59)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:114)
	at com.thoughtworks.xstream.converters.reflection.ReflectionConverter.marshal(ReflectionConverter.java:44)
	at com.thoughtworks.xstream.core.ReferenceByXPathMarshaller.convertAnother(ReferenceByXPathMarshaller.java:36)
	at com.thoughtworks.xstream.converters.reflection.ReflectionConverter$1.writeField(ReflectionConverter.java:78)
	at com.thoughtworks.xstream.converters.reflection.ReflectionConverter$1.visit(ReflectionConverter.java:59)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:114)
	at com.thoughtworks.xstream.converters.reflection.ReflectionConverter.marshal(ReflectionConverter.java:44)
	at com.thoughtworks.xstream.core.ReferenceByXPathMarshaller.convertAnother(ReferenceByXPathMarshaller.java:36)
	at com.thoughtworks.xstream.converters.reflection.ReflectionConverter$1.writeField(ReflectionConverter.java:78)
	at com.thoughtworks.xstream.converters.reflection.ReflectionConverter$1.visit(ReflectionConverter.java:59)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:114)
	at com.thoughtworks.xstream.converters.reflection.ReflectionConverter.marshal(ReflectionConverter.java:44)
	at com.thoughtworks.xstream.core.ReferenceByXPathMarshaller.convertAnother(ReferenceByXPathMarshaller.java:36)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:46)
	at com.thoughtworks.xstream.core.ReferenceByXPathMarshallingStrategy.marshal(ReferenceByXPathMarshallingStrategy.java:17)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:461)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:451)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:432)
	at com.baesystems.ai.analytics.smile.utils.SmileDataUtils.serializeTree(SmileDataUtils.java:243)
	at com.baesystems.ai.analytics.smile.utils.SmileDataUtils.createTrainingRecords(SmileDataUtils.java:235)
	at com.baesystems.ai.analytics.smile.classification.DecisionTreeClassifier.execute(DecisionTreeClassifier.java:118)
	at com.baesystems.ai.analytics.common.ModelingEngine.main(ModelingEngine.java:81)

I even tried serializing your test example
 AttributeDataset weather = arffParser.parse("./test-data/weather.arff");
            double[][] x = weather.toArray(new double[weather.size()][]);
            int[] y = weather.toArray(new int[weather.size()]);
            DecisionTree tree = new DecisionTree(x, y, 5, DecisionTree.SplitRule.GINI);
            XStream xstream = new XStream();
    		xstream.alias("tree", DecisionTree.class);
    		String xml = xstream.toXML(tree);
    		System.out.println(xml);

**Comment by haifengl** [comment]
Are you using 1.2.1? Please use 1.2.2, which fixed this issue.

**Comment by aminaaslam** [comment]
Thanks, it worked.

**Comment by aminaaslam** [comment]
Not relevant to this question. I have to generate PMML from the decision tree model. I know your API doesnot provide PMML support. Can you give me an insight as how should i go about doing it(generating the PMML)??

**Comment by haifengl** [comment]
Currently we don't expose the internal of decision trees. I can add a few methods for you to travel the decision tree. BTW, you want to export the model by PMML and then use the model in another package for prediction? Is there any difficult for you to use smile for prediction directly? Thanks!

**Comment by aminaaslam** [comment]
I would really appreciate if you can add methods to traverse the Decision Tree so i can export Decision Trees as PMML. I need PMML model so it can run on any system and is part of the requirement for my project. Then i will the predictions made by SMILE model and compare them with PMML predictions for verification. 
Please let me know how long would it take for you to expose the traversal functionality.
Thanks,

**Comment by haifengl** [comment]
How about we work together to add toPMML methods to DecisionTree and other algorithms? Create a fork and starts with the "root" member variable, you can generate the PMML easily. Thanks!

**Comment by aminaaslam** [comment]
ok cool i will do it. I will keep you posted.
Thanks for your prompt responses.
