### ISSUE TITLE
Normalizing data before giving it to ISOMap or LLE learner

### ISSUE THREAD

**Issue by aminaaslam** [haifengl/smile#172]
Hi Hai,
Its not an issue but a couple of questions that i have
1.I want to normalize my data before giving it to ISOMap or LLE. What is a good way of doing that in Smile?
2. I want to plot the coordinates that ISOMap or LLE generate what is a good and quick way of doing that in your wonderful framework? I am looking at PlotCanvas

Thanks,

**Comment by haifengl** [comment]
1. smile.math.Math has multiple ways to normalize the data (normalize, standardize, unitize, etc.) Please check out the Javadoc (http://haifengl.github.io/smile/api/java/index.html) for their difference.

2. See http://haifengl.github.io/smile/manifold.html how to plot the results (and also the nearest neighbor graph if needed).

**Comment by aminaaslam** [comment]
Thank you so much. As always this was very helpful

**Comment by aminaaslam** [comment]
Hi Hai,
I am trying to save the image generated by IsoMap in .png file but it keeps throwing this exception. Am i doing it correctly or i am missing something. Thanks,


  PlotCanvas plot = ScatterPlot.plot(learner.coordinates, '.', Color.BLUE);
 plot.save(new File("out.png"));

This is the excpetion that i am getting.
Exception in thread "main" java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at smile.plot.PlotCanvas.save(PlotCanvas.java:1069)
	at com.baesystems.ai.analytics.smile.dimensionality.reduction.ManifoldLearningFunction.saveImage(ManifoldLearningFunction.java:120)
	at com.baesystems.ai.analytics.smile.dimensionality.reduction.ManifoldLearningFunction.execute(ManifoldLearningFunction.java:98)
	at com.baesystems.ai.analytics.common.ModelingEngine.main(ModelingEngine.java:81)

**Comment by haifengl** [comment]
You probably try to do a headless plot on a server. If so, see the bottom of is page how to save headless plot:

http://haifengl.github.io/smile/faq.html

**Comment by aminaaslam** [comment]
hi Hai,
i changed it to headless plot because i dont want to use the swing UI. I just need to export the image to a png
`  PlotCanvas plot = ScatterPlot.plot(learner.coordinates, '.', Color.BLUE);
       Headless headless = new Headless(plot);
       headless.pack();
       headless.setVisible(true);

       plot.save(new java.io.File("headless.png"));`

But it keeps giving me the same exception. 
Exception in thread "main" java.lang.IllegalArgumentException: Width (20) and height (0) cannot be <= 0
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at smile.plot.PlotCanvas.save(PlotCanvas.java:1069)
	at com.baesystems.ai.analytics.smile.dimensionality.reduction.ManifoldLearningFunction.saveImage(ManifoldLearningFunction.java:115)
	at com.baesystems.ai.analytics.smile.dimensionality.reduction.ManifoldLearningFunction.execute(ManifoldLearningFunction.java:100)
	at com.baesystems.ai.analytics.common.ModelingEngine.main(ModelingEngine.java:81)

**Comment by aminaaslam** [comment]
Please ignore this. There was a problem with my environment
