### ISSUE TITLE
read.csv doesn't support string data

### ISSUE THREAD

**Issue by yiming-chen** [haifengl/smile#185]
I am trying to load a cvs file using read.csv. However, it doesn't seem to support string values.

**Comment by haifengl** [comment]
Can you share your code and some input sample?

**Comment by yiming-chen** [comment]
This is the layout of my cvs:

count_x	domain	perc_x	count_y
0	007safe.com	0	1
1	012.net.il	0.006111386	13


I am trying to load the data with:
val data = read.csv("data/domain_stat.csv", header=true)

This will return error message (it would work if I delete the "domain" column which is string):

java.lang.NumberFormatException: For input string: "007safe.com"
  at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
  at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
  at java.lang.Double.parseDouble(Double.java:538)
  at java.lang.Double.valueOf(Double.java:502)
  at smile.data.NumericAttribute.valueOf(NumericAttribute.java:62)
  at smile.data.parser.DelimitedTextParser.parse(DelimitedTextParser.java:372)
  at smile.data.parser.DelimitedTextParser.parse(DelimitedTextParser.java:259)
  at smile.data.parser.DelimitedTextParser.parse(DelimitedTextParser.java:216)
  at smile.data.parser.DelimitedTextParser.parse(DelimitedTextParser.java:196)
  at smile.read$.table(package.scala:195)
  at smile.read$.csv(package.scala:200)

**Comment by haifengl** [comment]
Read.csv doesn't guess the data type. You should provide an array of Attribute to tell it the data type of each column.

**Comment by yiming-chen** [comment]
Thanks. I am trying to find more tutorial/sample codes for Scala API on this. Do you know where I could find them other than the "3rd party tutorial" link?

**Comment by haifengl** [comment]
Don't know if you check out the user guide at http://haifengl.github.io/smile/

For your use case, check out this example:

https://github.com/haifengl/smile/blob/master/benchmark/src/main/scala/smile/benchmark/Airline.scala#L48

**Comment by yiming-chen** [comment]
Thanks!

**Comment by dopicar** [comment]
I came here as well after encountering this error. While the culprit is quite easy to understand, the official documentation offers little explanation of the need to provide the file's schema (where? how?). 

Automatic parsing of CSV (or at least suggestion for user adjudication) could be very helpful to facilitate work.

**Comment by salamanders** [comment]
I ran into the same issue. I got it to load into a DataFrame:

```kotlin
val trainingFrame: DataFrame = Read.csv(/* path = */ "data/train.csv", /* format = */
    CSVFormat.Builder.create().setHeader().setSkipHeaderRecord(true).build()
)
```

Which is great, it correctly figured out that some columns were Strings, some were Boolean, some were Double.  It even handled Nulls just fine.

... now what?    The following (understandably) dies on the first String in 

```kotlin
val prop = Properties().apply {
    setProperty("smile.random.forest.trees", "200")
}
val forest: RandomForest = RandomForest.fit(
    /* formula = */ Formula.lhs("TheTargetColumn"), 
    /* data = */ trainingFrame, /* params = */ prop)!!
```

**Comment by haifengl** [comment]
`dataFrame.factorize()` will convert string columns to categorical variables.

**Comment by salamanders** [comment]
I'm having trouble with that due to nulls (blank strings) in my input set.

```kotlin
val trainingFrame: DataFrame = Read.csv(
        "data/train.csv",
        CSVFormat.Builder.create().setHeader().setSkipHeaderRecord(true).build()
    )
```
works fine.  But then when I try to run either a `omitNullRows()` or a `factorize()` on it, I get an exception.

omitNullRows:
> Exception in thread "main" java.lang.ClassCastException: class smile.data.vector.VectorImpl cannot be cast to class smile.data.vector.BooleanVector (smile.data.vector.VectorImpl and smile.data.vector.BooleanVector are in unnamed module of loader 'app')
	at smile.data.DataFrameImpl$DataFrameRow.getBoolean(DataFrameImpl.java:608)
	at smile.data.DataFrameImpl.<init>(DataFrameImpl.java:278)
	at smile.data.DataFrameImpl.<init>(DataFrameImpl.java:216)
	at smile.data.DataFrame.of(DataFrame.java:1537)
	at smile.data.DataFrame.omitNullRows(DataFrame.java:105)
	at MainKt.main(Main.kt:110)
	at MainKt.main(Main.kt)

factorize: 
> Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:52)
	at java.base/java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47)
	at java.base/java.util.TimSort.binarySort(TimSort.java:296)
	at java.base/java.util.TimSort.sort(TimSort.java:221)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392)
	at java.base/java.util.stream.DistinctOps$1$2.end(DistinctOps.java:168)
	at java.base/java.util.stream.Sink$ChainedInt.end(Sink.java:290)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at smile.data.DataFrame.lambda$factorize$6(DataFrame.java:992)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at smile.data.DataFrame.factorize(DataFrame.java:1003)
	at MainKt.main(Main.kt:111)
	at MainKt.main(Main.kt)
