### ISSUE TITLE
PCA:Array Index Out of Bounds

### ISSUE THREAD

**Issue by aminaaslam** [haifengl/smile#200]
Hi Hai,
I am running PCA(Principal Component Analysis) on my data set with following parameters
Correlation: true
Dimensions: 2
But i am running into this issue. This is the same issue that i am getting on ISOMap and LLE. Does this means this numeric stability issue will affect all of your algorithms. Do you have any time frame for fixing this problem??
Thanks,
Amina

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 194
	at smile.math.matrix.EigenValueDecomposition.tql2(EigenValueDecomposition.java:1382)
	at smile.math.matrix.EigenValueDecomposition.decompose(EigenValueDecomposition.java:992)
	at smile.math.matrix.EigenValueDecomposition.decompose(EigenValueDecomposition.java:960)
	at smile.projection.PCA.<init>(PCA.java:170)
	at com.baesystems.ai.analytics.smile.dimensionality.reduction.PCAProjection.reduce(PCAProjection.java:73)
	at com.baesystems.ai.analytics.smile.dimensionality.reduction.DimensionReductionFunction.execute(DimensionReductionFunction.java:89)
	at com.baesystems.ai.analytics.common.ModelingEngine.main(ModelingEngine.java:81)

**Comment by haifengl** [comment]
The new matrix library will be ready soon. BTW, which smile version do you use? I couldn't find meaning lines in EigenValueDecomposition.java according to your stack trace.

**Comment by haifengl** [comment]
Sorry, I made so many changes recently. It is why I couldn't find the location raising the exception. The function tql2 is a standard implementation, same as you can find in python, c, or other packages. It is interesting that the other packages don't have this issue. I guess that their preprocessing is different thus that the matrix feeded into eigen decomposition is different and doesn't trigger this issue.

I have added some safe guard to avoid the out of bound index. Meanwhile, the BLAS/LAPACK based matrix decompositions are ready. All you need is to add smile-netlib to your dependency list. For now, you have to build the master by yourself. Also make sure that you have BLAS/LAPACK available on your PATH. See https://github.com/haifengl/smile/blob/master/netlib/src/main/java/smile/netlib/package-info.java for details.

**Comment by aminaaslam** [comment]
Thanks i will check it out and will add my observations here. I was using version 2.0.0 of Smile. But for this change i will switch to Version 3 and work on that.
Thanks you once again.

**Comment by haifengl** [comment]
Please use the master branch and build by yourself for now. The new features are not released to maven central repo yet. Also make sure you have BLAS/LAPACK/ARPACK installed on your machine. Check the link in previous comment for details. Thanks!

**Comment by aminaaslam** [comment]
Hi Hai,
I am using CentOS 7 and installed following binaries using yum
sudo yum install numpy scipy blas-devel lapack-devel atlas-devel 
and  i cloned smile's Master branch and when i do 
sbt package 
it gives me this error 
[error] /run/media/root/BackUpData/smile/scala/src/main/scala/smile/math/Operators.scala:233: value svd is not a member of object smile.math.matrix.Lanczos
[error]   def svd(A: DenseMatrix, k: Int) = Lanczos.svd(A, k)
[error]                                             ^
[error] one error found
[error] (scala/compile:compileIncremental) Compilation failed
[error] Total time: 6 s, completed Jul 24, 2017 2:46:40 PM

What am i missing ??
Thanks!!

**Comment by haifengl** [comment]
Sorry I forgot to commit some file. I will do it ASAP when I can access a computer.

**Comment by haifengl** [comment]
I have pushed all commits to master. Please git pull and build again. Thanks!

**Comment by aminaaslam** [comment]
Hi Hai,
I was able to build smile 1.4.0 after your check in. So i tested following three algorithms using the new version but i am getting these errors 

PCA: 
java.lang.ArrayIndexOutOfBoundsException: 100
        at smile.math.matrix.JMatrix.tql2(JMatrix.java:1749)
	at smile.math.matrix.JMatrix.eigen(JMatrix.java:1368)
	at smile.projection.PCA.<init>(PCA.java:173)
	at com.amina.jsat.evaluation.SmileCardDataTest.runPCAOnCard(SmileCardDataTest.java:90)

On KPCA i am getting this exception but i will try it on a bigger machine. I tried it with 6G RAM and even this its failing. 
java.lang.OutOfMemoryError: Java heap space

	at smile.math.matrix.JMatrix.<init>(JMatrix.java:80)
	at smile.math.matrix.Factory.matrix(Factory.java:105)
	at smile.math.matrix.Matrix.zeros(Matrix.java:100)
	at smile.projection.KPCA.<init>(KPCA.java:136)
	at com.amina.jsat.evaluation.SmileCardDataTest.runKPCAOnCard(SmileCardDataTest.java:67)

PPCA completes in 1s and 149ms.

I am also attaching performance results from JSAT's evaluation. I am using the same dataset for evaluating both libraries.

Card Data Execution Time:
----------------------------------
IsoMap: 26 minutes with 12GB
PCA:   823ms with 6G RAM
KPCA:  17secs and 114ms with 6G RAM
tSNE : 1min 55secs with 6G RAM

**Comment by aminaaslam** [comment]
I am attaching the data file for you
[card.csv.gz](https://github.com/haifengl/smile/files/1174580/card.csv.gz)

**Comment by haifengl** [comment]
The error shows that you have not use the latest netlib base matrix computation yet. Did you include smile-netlib as the dependency?

**Comment by haifengl** [comment]
Please do the following in the smile shell:

```
smile> val card = read.csv("/Users/hli/Downloads/card.csv")
smile> card.summary
```

Several observations from the output. You have several columns (e.g. V25, V26, V37) of all zeros, which will cause NaN values when calculating standard deviations. I guess that this was the root cause of pca(x, cor=true) failure. It is okay for pca(x, cor=false) because it does SVD without computing correlation matrix. PPCA is fine too as it doesn't compute standard deviations.

Second, your variables have very different ranges (PCA with covariance matrix doesn't make sense in this case). Please use cor = true for PCA (after removing constant columns). For KPCA, what's your kernel (and hyper-parameters)? In general, KPCA won't generate good results for common kernels (Gaussian, polynomial etc.) in your case. 

IsoMap doesn't work well either for your data (it is essentially same as KPCA with a particular kernel).

Maybe some software doesn't throw exceptions for your data, it doesn't mean that the results are meaningful. 

On my (old) laptop (without power cord), pca can finish in 330 ms for your data with smile-netlib.

**Comment by aminaaslam** [comment]
So i have added smile-netlib 1.4.0 jar on my classpath but i am getting this error. Is LAPACK not part of your jar. Do i need to add that to my classpath aswell. if yes then what version ?

java.lang.NoClassDefFoundError: com/github/fommil/netlib/LAPACK

	at smile.netlib.NLMatrix.eigen(NLMatrix.java:435)
	at smile.projection.PPCA.<init>(PPCA.java:153)
	at com.amina.jsat.evaluation.SmileCardDataTest.runPPCAOnCard(SmileCardDataTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: com.github.fommil.netlib.LAPACK
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335

**Comment by haifengl** [comment]
You cannot just directly add jar. Smile-Netlib depends on third party library. You should use sbt or maven to manage library dependencies

**Comment by aminaaslam** [comment]
Hi Hai,
I was able to run PCA, PPCA algorithms on my data that i shared with you. Running into OOM issues with ISOMap and KPCA. Will try it on a bigger machine. 
But when i ran LLE this is the exception that i am getting.  This i believe is the same exception that i was getting with older version of Smile.

java.lang.RuntimeException: Matrix is singular.

	at smile.netlib.LU.solve(LU.java:115)
	at smile.netlib.LU.solve(LU.java:102)
	at smile.manifold.LLE.<init>(LLE.java:180)
	at com.amina.jsat.evaluation.SmileCardDataTest.runLLEOnCard(SmileCardDataTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by haifengl** [comment]
Did you remove the constant columns?

**Comment by haifengl** [comment]
BTW, this time the error is from NLMatrix/LAPACK. Previously, the same error came from JMatrix (our pure java implementation). So I am pretty sure that it is not a bug in our code. The matrix is singular indeed here.

**Comment by haifengl** [comment]
LLE firstly solves a linear system for each point with its neighbors (the LU part you see in the log). Since your data is very sparse (a lot of zeros), given a small number of neighbors, the matrix can easily have a column of all zeros. It is why the matrix is singular.

**Comment by aminaaslam** [comment]
If i increase the number of neighbors would it help. In the above experiment i used k=5 ? 
I also try it on another dataset and see what it does.

**Comment by aminaaslam** [comment]
Even with k =10 it gives the same problem on this dataset.

**Comment by haifengl** [comment]
Your data is so sparse, k = 10 is not solution. Why not read the paper and get yourself familiar with these algorithms? LLE is not suitable here.

**Comment by aminaaslam** [comment]
Hi Hai, Please dont think that i am trying to undermine your software all i am trying to do is evaluate it with different datasets that i have to make a determination whether to use it with my datasets or not.

        kernel = new GaussianKernel(Math.sqrt(0.5));
        KPCA kpca = new KPCA(data,kernel,2,0.001);

I am getting this error 
java.lang.NegativeArraySizeException
	at smile.math.matrix.JMatrix.<init>(JMatrix.java:80)
	at smile.math.matrix.Factory.matrix(Factory.java:105)
	at smile.math.matrix.Matrix.zeros(Matrix.java:100)
	at smile.projection.KPCA.<init>(KPCA.java:136)
	at com.amina.jsat.evaluation.SmilePaymentDataTest.runKPCA(SmilePaymentDataTest.java:72)

**Comment by haifengl** [comment]
The error means that the matrix is too large (array length overflows so that Java thinks it is a negative number)

**Comment by haifengl** [comment]
I suggest that your target should be evaluate if an algorithm is suitable for your data, not if a software is suitable. It is always good to understand the algorithms first.
