### ISSUE TITLE
Failed to run FPGrowth on multi-core

### ISSUE THREAD

**Issue by kalki123123** [haifengl/smile#300]
I end up with the following exception when I try to create an instance of ARM.

ERROR smile.association.FPGrowth - Failed to run FPGrowth on multi-core
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 0
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at smile.util.MulticoreExecutor.run(MulticoreExecutor.java:107)
	at smile.association.FPGrowth.grow(FPGrowth.java:298)
	at smile.association.FPGrowth.learn(FPGrowth.java:178)
	at smile.association.FPGrowth.buildTotalSupportTree(FPGrowth.java:166)
	at smile.association.ARM.learn(ARM.java:129)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at smile.association.TotalSupportTree.add(TotalSupportTree.java:114)
	at smile.association.TotalSupportTree.add(TotalSupportTree.java:121)
	at smile.association.TotalSupportTree.add(TotalSupportTree.java:121)
	at smile.association.TotalSupportTree.add(TotalSupportTree.java:121)
	at smile.association.TotalSupportTree.add(TotalSupportTree.java:121)
	at smile.association.TotalSupportTree.add(TotalSupportTree.java:121)
	at smile.association.TotalSupportTree.add(TotalSupportTree.java:121)
	at smile.association.TotalSupportTree.add(TotalSupportTree.java:121)
	at smile.association.TotalSupportTree.add(TotalSupportTree.java:121)
	at smile.association.TotalSupportTree.add(TotalSupportTree.java:96)
	at smile.association.FPGrowth.grow(FPGrowth.java:345)
	at smile.association.FPGrowth.grow(FPGrowth.java:312)

Please let me know what could be the reason and solution if any. 

Environment : 
JDK 1.8

**Comment by haifengl** [comment]
What's your input data and how do you call FPGrowth?

**Comment by haifengl** [comment]
The input should be sparse. For example, if a transaction has items 1 and 12, then the input row should be just `[1, 12]`. I guess that your input is something like `[0, 1, 0, 0, ..., 1, 0, ...]`.
