### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException emerges

### ISSUE THREAD

**Issue by gypsysunny** [haifengl/smile#301]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at smile.math.distance.EditDistance$BRF1.f(EditDistance.java:403)
	at smile.math.distance.EditDistance.br(EditDistance.java:369)
	at smile.math.distance.EditDistance.d(EditDistance.java:143)
	at smile.math.distance.EditDistance.d(EditDistance.java:42)
	at smile.neighbor.BKTree.search(BKTree.java:203)

val neighborList1 = List.empty[Neighbor[String, String]]
bkTreePortName.range(e, dist, neighborList1.asJava)

can you please try to figure out the root clause? Thank you in advance.

**Comment by haifengl** [comment]
Can you provide more code snippets of your program? What're `bkTreePortName`, `e`, and `dist`?
