### ISSUE TITLE
Class smile.neighbor.CoverTree does not implement Serializable or externalizable

### ISSUE THREAD

**Issue by ryujin88** [haifengl/smile#302]
## Expected behavior

KNN class is serializable, so I'd expect to be able to serialize it.

## Actual behavior

Serializer throws an exception while serializing a KNN instance, here is the relevant stack trace:
```
java.lang.RuntimeException: Class smile.neighbor.CoverTree does not implement Serializable or externalizable
	at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:144)
	at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:129)
	at org.nustaq.serialization.FSTObjectOutput.getFstClazzInfo(FSTObjectOutput.java:534)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:416)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:369)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectFields(FSTObjectOutput.java:664)
	at org.nustaq.serialization.FSTObjectOutput.defaultWriteObject(FSTObjectOutput.java:546)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectWithContext(FSTObjectOutput.java:458)
	at org.nustaq.serialization.FSTObjectOutput.writeObjectInternal(FSTObjectOutput.java:327)
	at org.nustaq.serialization.FSTObjectOutput.writeObject(FSTObjectOutput.java:294)
```

## Code snippet

I'm serializing using: 
```
        <dependency>
            <groupId>de.ruedigermoeller</groupId>
            <artifactId>fst</artifactId>
            <version>2.57</version>
        </dependency>
```

```
public static void main(String[] args) {
    final double[][] data = new double[5][5];
    final int[] classification = new int[5];
   // generate enough classes so KNN doesn't complain
    classification[1] = 1;
    classification[2] = 2;
    final KNN<double[]> knn = new KNN<>(data, classification, new EuclideanDistance());

    try {
      final FSTObjectOutput fst = new FSTObjectOutput(new FileOutputStream(new File("file.dat")));
      fst.writeObject(knn); // << throws Class smile.neighbor.CoverTree does not implement Serializable or externalizable
    } catch (IOException e) {
      e.printStackTrace();
    }

  }
```

## Input data

Doesn't matter

## Information
- Which Smile version: 1.5.1

**Comment by ryujin88** [comment]
It shouldn't be a problem. 

Do you suggest any other way to serialize the KNN model? or should I simply discard the idea of serialization of the KNN model?

**Comment by haifengl** [comment]
I have make all nearest neighbor search data structures, including CoverTree, serializable. The changes will be available in the next release.
