### ISSUE TITLE
Wrong IllegalArgumentException: The gamma function is negative

### ISSUE THREAD

**Issue by MZinchenko** [haifengl/smile#355]
## Expected behaviour
Very small negative value of gamma function must be regarded as zero value.

## Actual behaviour
**Gamma::lgamma** throws exception when **fg** is -6.070665071826722E-166
```
Exception in thread "main" java.lang.IllegalArgumentException: The gamma function is negative
	at smile.math.special.Gamma.lgamma(Gamma.java:109)
	at smile.math.special.Beta.regularizedIncompleteBetaFunction(Beta.java:69)
```

This behaviour is wrong and very annoying. Exception drops on random row of huge dataset and result disappear. I think this situation can be logged as a last resort.

## Information
Smile 1.5.1

**Comment by haifengl** [comment]
Thanks. The problem is more tricky than what you suggest. I will look into this.

**Comment by haifengl** [comment]
The problem comes from Gamma.lgamma(-111.0). And python and R fails too with this value for lgamma. So first of all, it is not a bug of lgamma. The input alpha actually should be a positive value from LASSO's point of view. I guess that your sample size is smaller than dimensionality. Is it right? Our algorithm is not designed for this case.

**Comment by MZinchenko** [comment]
> I guess that your sample size is smaller than dimensionality

Yeah, this situation othen for my data (categorical features). 
Fact count and dimensions are very close.

I tried two approaches to solve problem:
1) put data into regression (f.e. LASSO) as is, and then shrink model
2) do some PCA projection, and then do regression

But first way more accurate at most, so I can not refuse it at now.

**Comment by haifengl** [comment]
`gamma` function part is for p-value calculation. If it is not important to you, try commenting that part out.

**Comment by MZinchenko** [comment]
Ok. I think we can close this issue.
I see that my use case is wrong.
May be some parameter assertion in LASSO, RLS and other regressions using `regularizedIncompleteBetaFunction` will be useful?
Or may be add assertion in `regularizedIncompleteBetaFunction` for `alpha`? But assertion in this function is not obvious as for me (`alpha` can be calculated different way).
