### ISSUE TITLE
NLP  - nullpointer exception when searching on simplecorpus

### ISSUE THREAD

**Issue by Xyclade** [haifengl/smile#39]
When I execute the following code the search method throws a nullpointer exception:
 *note, its scala*
```scala
 val nlp = new SimpleCorpus()
 nlp.add("test","test2","The cake is a lie and tastes bad")
var possiblyEmptyIterator = nlp.search("good")
```

I had expected it to return an empty iterator, but instead it gives the following exception:

Exception in thread "main" java.lang.NullPointerException
	at java.util.ArrayList.<init>(ArrayList.java:164)
	at smile.nlp.SimpleCorpus.search(SimpleCorpus.java:237)
	at Main$.delayedEndpoint$Main$1(package.scala:31)
	at Main$delayedInit$body.apply(package.scala:9)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at Main$.main(package.scala:9)
	at Main.main(package.scala)

After looking into the SimpleCorpus I found why this happens: without checking you get the search term from the HashMap, thus if it is not there, the hashMap get call returns null, which is then fed into the constructor of the arrayList. 

The same construction is used in all SimpleCorpus search methods.

My suggested fix would be to check before getting from the HashMap, if it contains the key. This way you do not need to store the (possible null) list in a local variable to check for null.
```java
 public Iterator<Text> search(String term) {
    	ArrayList<Text> hits = new ArrayList<Text>(invertedFile.get(term));
        return hits.iterator();
    }
```
then becomes
```java
public Iterator<Text> search(String term) {
        if (invertedFile.containsKey(term))
        {
            ArrayList<Text> hits = new ArrayList<Text>(invertedFile.get(term));
            return hits.iterator();
        }
        else
        {
            return Collections.emptyIterator();
        }
    }
```
Disclaimer: I havent thoroughly tested the code!

**Comment by haifengl** [comment]
Thanks! Can you make a pull request?
