### ISSUE TITLE
LibSvmParser throwing exception for non-numeric values for point-notated labels

### ISSUE THREAD

**Issue by Wolfonye** [haifengl/smile#404]
## Expected behaviour

Error-free parsing.

## Actual behaviour
I was trying to parse some data with *LibsvmParser.parse(File)* and encountered:

    Exception in thread "main" java.lang.IllegalArgumentException: The response variable is not numeric.
	at smile.data.SparseDataset.set(SparseDataset.java:225)
	at smile.data.parser.LibsvmParser.parse(LibsvmParser.java:155)
	at smile.data.parser.LibsvmParser.parse(LibsvmParser.java:102)

for input-rows that look like this:

    -1.0 1:1 2:2 3:1 4:1 5:1 6:1 7:1 8:2 [...]

which works just fine if I change -1.0 to -1.

Interestingly I get:

    Exception in thread "main" java.lang.NumberFormatException: For input string: "1.0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at smile.data.parser.LibsvmParser.parse(LibsvmParser.java:151)
	at smile.data.parser.LibsvmParser.parse(LibsvmParser.java:102)

for:

    1.0 8:1 56:1 154:1 [...]

I wonder if this is by purpose or if it's a bug. One way or the other "The response variable is not numeric." might be a slightly missleading error message.

(OracleJDK 11 with Smile-Version: 1.5.2 on Win10)

(Many thanks for the great library btw :) )

**Comment by afindert** [comment]
I'm trying to use libsvm data for SV regression and was not able to parse labels as real values even if the samples contain real values
parsing this example data:
1.0 1:1.0 2:2.0 3:3.0
2.1 1:2.1 2:4.1 3:8.1
throws "java.lang.IllegalArgumentException: The response variable is not numeric."

it works  with integer labels, even when the samples are real values

**Comment by haifengl** [comment]
@afindert Check your data, which may contain invisible character.

**Comment by afindert** [comment]
- data sets are clean, no invisible data
- data sets with integer labels are from the same source and do work

**Comment by haifengl** [comment]
The parser tries to determine that the label is integer or real value by testing the first token. Is the label of the first row is integer? Or you have some header/comment lines? It is better to share some of your data. Otherwise, it is hard to guess what's wrong.

**Comment by afindert** [comment]
Here is 1 data set I tried to do the SVR for. All sample and label values are real.
[SVR_data.libsvm.zip](https://github.com/haifengl/smile/files/3470688/SVR_data.libsvm.zip)

**Comment by haifengl** [comment]
I found the bug. Will fix soon. Thanks
