### ISSUE TITLE
LogisticRegression training can fail on multi-core

### ISSUE THREAD

**Issue by twotabbies** [haifengl/smile#458]
When running `sbt '; testOnly smile.classification.LogisticRegressionTest'` throws exceptions. It's a small fix; PR to follow.

## Expected behaviour

Test will run without exceptions.

## Actual behaviour

Many exceptions are printed.
`Caused by: java.lang.ArrayIndexOutOfBoundsException: 1050
        at smile.classification.LogisticRegression$MultiClassObjectiveFunction$FTask.call(LogisticRegression.java:688)
        at smile.classification.LogisticRegression$MultiClassObjectiveFunction$FTask.call(LogisticRegression.java:659)`

## Information

Smile 1.5.3 on a Debion derivative.

**Comment by twotabbies** [comment]
I think this is fixed. now.
