### ISSUE TITLE
BaseVector toIntArray UnsupportedOperationException in RandomForest

### ISSUE THREAD

**Issue by alabadie** [haifengl/smile#513]
Hi everyone, this is my first time posting an issue on GitHub.

## Case

I am trying to use Smile library to train random forest classifiers on various data sets.

## Issue

The RandomForest.fit() method always throw: 
java.lang.UnsupportedOperationException
	at smile.data.vector.BaseVector.toIntArray(BaseVector.java:90)
	at smile.data.vector.BaseVector.toIntArray(BaseVector.java:82)
	at smile.classification.ClassLabels.fit(ClassLabels.java:121)
	at smile.classification.RandomForest.fit(RandomForest.java:306)
	at smile.classification.RandomForest.fit(RandomForest.java:237)
	at smile.classification.RandomForest.fit(RandomForest.java:211)

When looking into the Smile code I noticed that ClassLabels.fit always call BaseVector.toIntArray that will always throw that exception. Does that mean that RandomForest is not operational at the moment ? 

## Information

- Oracle jdk 8
- Smile 2.0.0
- Mac OS X 10.15.2
- Working with IDEA Intellij 2019.3.1 Ultimate

**Comment by haifengl** [comment]
Your data may have missing values or not integral type (String?). You can convert Strings to int if you define the measure as `nominal` when loading data (suppose csv). Or `DataFrame.nominal()` tries to convert all string columns (or selected one by arguments).
