### ISSUE TITLE
Pearson correlation coefficient test: java.lang.IllegalArgumentException: The gamma function is negative

### ISSUE THREAD

**Issue by Brandonage** [haifengl/smile#560]
### Expected behaviour
Getting the results of the Pearson correlation coefficient test
`double corrCoefficient = CorTest.pearson(invertedXs[c], y).cor;`

### Actual behaviour
Exception thrown:

`java.lang.IllegalArgumentException: The gamma function is negative: -3.544907701811049
	at smile.math.special.Gamma.lgamma(Gamma.java:111) ~[smile-math-2.2.2.jar:2.2.2]
	at smile.math.special.Beta.regularizedIncompleteBetaFunction(Beta.java:83) ~[smile-math-2.2.2.jar:2.2.2]
	at smile.stat.hypothesis.CorTest.pearson(CorTest.java:157) ~[smile-math-2.2.2.jar:2.2.2]`

All the calculations done until that point are lost. 

### SMILE version

SMILE 2.2.2

**Comment by haifengl** [comment]
Can you please provide input data for testing? Thanks.

**Comment by Brandonage** [comment]
Sorry about that. I have debugged this problem more and turns out the input for the pearson function is empty due to a bug in our data preparation. I'll close the issue.
