### ISSUE TITLE
Using Logistic Regression multiclass in Smile1.5.3 : java.lang.ArrayIndexOutOfBoundsException: 3

### ISSUE THREAD

**Issue by stenpiren** [haifengl/smile#577]
I am trying to do multiclass classification using logistic regression in Smile 1.5.3. 

Essentially I am using X as double[][] and y as int[]. When initiating the model with X and y, the execution stops with:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at smile.classification.LogisticRegression$MultiClassObjectiveFunction.f(LogisticRegression.java:841)
	at smile.math.Math.min(Math.java:4556)
	at smile.classification.LogisticRegression.<init>(LogisticRegression.java:319)
	at smile.classification.LogisticRegression.<init>(LogisticRegression.java:231)
	at smile.classification.LogisticRegression.<init>(LogisticRegression.java:206)
	at demo.main(demo.java:125)
```

I normally pass on the data and check log error as follows:
```

        LogisticRegression model= new LogisticRegression(X, y);
        int error=0;

        for (int i = 0; i < X.length; i++) {

            if (model.predict(X[i]) != y[i]) {
                error++;
            }
        }

        System.out.println("Error: " + error);
```

Any clue why that error is thrown? It seems to also point out at the ```init``` in ```LogisticRegression``` as well as the ```MultiClassObjectiveFunction```.

I used a dummy case with 3 classes and I intend to increase the number of classes past 10. Any clue why it is not working?

**Comment by haifengl** [comment]
we don't support 1.x any longer. BTW, i guess that your class labels are not in [0, k) range.
