### ISSUE TITLE
Confusing exception when MKL is not found

### ISSUE THREAD

**Issue by genmeblog** [haifengl/smile#588]
**Describe the bug**
When MKL is not found an exception is printed. This is confusing since library fallbacks to OpenBLAS in this case. 

```
0:27:21.734 [main] DEBUG smile.math.blas.LAPACK - Failed to create MKL instance:  {  }
java.lang.ClassNotFoundException: smile.math.blas.mkl.MKL
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:340)
	at smile.math.blas.LAPACK.MKL(LAPACK.java:48)
```

**Expected behavior**
Just give information about OpenBLAS usage instead of MKL

**Additional context**
- OpenJDK: OpenJDK 64-Bit Server VM (build 14.0.1+7-Ubuntu-1ubuntu1, mixed mode, sharing)
- SMILE: 2.5.0
- Ubuntu 20.04.01 on WSL2 (Windows 10)
- Called from Clojure with deps:

```clojure
[com.github.haifengl/smile-interpolation "2.5.0" ]
[com.github.haifengl/smile-core "2.5.0"]
```

**Comment by haifengl** [comment]
It is for debugging only. It won't show unless you set your log level to DEBUG or TRACE.
