### ISSUE TITLE
Tests fail on JDK15

### ISSUE THREAD

**Issue by lukehutch** [haifengl/smile#605]
I tried running the KDTree tests from git latest on JDK15, but got this:

```
[debug] Test run started
[debug] Test smile.neighbor.KDTreeTest.testKnn started
[error] Test smile.neighbor.KDTreeTest.testKnn failed: java.lang.ClassCastException: class [Ljava.lang.Comparable; cannot be cast to class [Lsmile.neighbor.NeighborBuilder; ([Ljava.lang.Comparable; is in module java.base of loader 'bootstrap'; [Lsmile.neighbor.NeighborBuilder; is in unnamed module of loader sbt.internal.LayeredClassLoader @2ba93c9d), took 0.042 sec
[error]     at smile.neighbor.LinearSearch.knn(LinearSearch.java:123)
[error]     at smile.neighbor.KDTreeTest.testKnn(KDTreeTest.java:88)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:564)
[error]     ...
[debug] Test smile.neighbor.KDTreeTest.testKnn finished, took 0.044 sec
[debug] Test smile.neighbor.KDTreeTest.testGaussianMixture started
[error] Test smile.neighbor.KDTreeTest.testGaussianMixture failed: java.lang.ClassCastException: class [Ljava.lang.Comparable; cannot be cast to class [Lsmile.neighbor.NeighborBuilder; ([Ljava.lang.Comparable; is in module java.base of loader 'bootstrap'; [Lsmile.neighbor.NeighborBuilder; is in unnamed module of loader sbt.internal.LayeredClassLoader @2ba93c9d), took 0.37 sec
[error]     at smile.neighbor.KDTree.knn(KDTree.java:388)
[error]     at smile.neighbor.KDTreeTest.testGaussianMixture(KDTreeTest.java:160)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:564)
[error]     ...
[debug] Test smile.neighbor.KDTreeTest.testGaussianMixture finished, took 0.371 sec
[debug] Test smile.neighbor.KDTreeTest.testRange started
[debug] Test smile.neighbor.KDTreeTest.testRange finished, took 0.258 sec
[debug] Test smile.neighbor.KDTreeTest.testUSPS started
[error] Test smile.neighbor.KDTreeTest.testUSPS failed: java.lang.ClassCastException: class [Ljava.lang.Comparable; cannot be cast to class [Lsmile.neighbor.NeighborBuilder; ([Ljava.lang.Comparable; is in module java.base of loader 'bootstrap'; [Lsmile.neighbor.NeighborBuilder; is in unnamed module of loader sbt.internal.LayeredClassLoader @2ba93c9d), took 4.909 sec
[error]     at smile.neighbor.KDTree.knn(KDTree.java:388)
[error]     at smile.neighbor.KDTreeTest.testUSPS(KDTreeTest.java:226)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:564)
[error]     ...
[debug] Test smile.neighbor.KDTreeTest.testUSPS finished, took 4.91 sec
[debug] Test smile.neighbor.KDTreeTest.testBenchmark started
[debug] Test smile.neighbor.KDTreeTest.testBenchmark finished, took 0.103 sec
[debug] Test smile.neighbor.KDTreeTest.testNearest started
[debug] Test smile.neighbor.KDTreeTest.testNearest finished, took 0.079 sec
[debug] Test run finished: 3 failed, 0 ignored, 6 total, 5.776s
[error] Failed: Total 6, Failed 3, Errors 0, Passed 3
[error] Failed tests:
[error]         smile.neighbor.KDTreeTest
[error] (scala / Compile / compileIncremental) Compilation failed
[error] (core / Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 12 s, completed Oct 26, 2020, 7:36:56 AM
```

The problem is code like this in `KDTree.java`:

```
HeapSelect<NeighborBuilder<double[], E>> heap = new HeapSelect<>(k);
```

which constructor calls

```
this((T[]) new Comparable[k])
```

then later `KDTree.java` calls `heap.toArray()`, which should have type `NeighborBuilder<double[], E>[]`, but is actually `Comparable<?>[]` since generic arrays are not supported in Java.

Apparently recent JDKs are being more strict in checking for this situation.

The solution would probably be to fix the `HeapSelect` constructor to take an array that is already populated (or at least already allocated), rather than just the parameter `int k`.

**Comment by lukehutch** [comment]
Actually the test fails even on JDK 8:

```
[debug] Test smile.neighbor.KDTreeTest.testKnn started
[error] Test smile.neighbor.KDTreeTest.testKnn failed: java.lang.ClassCastException: [Ljava.lang.Comparable; cannot be cast to [Lsmile.neighbor.NeighborBuilder;, took 0.042 sec
[error]     at smile.neighbor.LinearSearch.knn(LinearSearch.java:123)
[error]     at smile.neighbor.KDTreeTest.testKnn(KDTreeTest.java:88)
[error]     ...
[debug] Test smile.neighbor.KDTreeTest.testKnn finished, took 0.044 sec
[debug] Test smile.neighbor.KDTreeTest.testGaussianMixture started
[error] Test smile.neighbor.KDTreeTest.testGaussianMixture failed: java.lang.ClassCastException: [Ljava.lang.Comparable; cannot be cast to [Lsmile.neighbor.NeighborBuilder;, took 0.213 sec
[error]     at smile.neighbor.KDTree.knn(KDTree.java:388)
[error]     at smile.neighbor.KDTreeTest.testGaussianMixture(KDTreeTest.java:160)
[error]     ...
[debug] Test smile.neighbor.KDTreeTest.testGaussianMixture finished, took 0.214 sec
[debug] Test smile.neighbor.KDTreeTest.testRange started
[debug] Test smile.neighbor.KDTreeTest.testRange finished, took 0.163 sec
[debug] Test smile.neighbor.KDTreeTest.testUSPS started
[error] Test smile.neighbor.KDTreeTest.testUSPS failed: java.lang.ClassCastException: [Ljava.lang.Comparable; cannot be cast to [Lsmile.neighbor.NeighborBuilder;, took 5.748 sec
[error]     at smile.neighbor.KDTree.knn(KDTree.java:388)
[error]     at smile.neighbor.KDTreeTest.testUSPS(KDTreeTest.java:226)
[error]     ...
[debug] Test smile.neighbor.KDTreeTest.testUSPS finished, took 5.749 sec
[debug] Test smile.neighbor.KDTreeTest.testBenchmark started
[debug] Test smile.neighbor.KDTreeTest.testBenchmark finished, took 0.124 sec
[debug] Test smile.neighbor.KDTreeTest.testNearest started
[debug] Test smile.neighbor.KDTreeTest.testNearest finished, took 0.071 sec
[debug] Test run finished: 3 failed, 0 ignored, 6 total, 6.374s
[error] Failed: Total 6, Failed 3, Errors 0, Passed 3
[error] Failed tests:
[error]         smile.neighbor.KDTreeTest
```

This is an unmodified version of SMILE from git.

**Comment by haifengl** [comment]
I made some change for safer generic array creation. Please have a try on JDK15. Thanks.

**Comment by lukehutch** [comment]
With JDK15 and the latest git version, the KDTree tests now pass. I'm running the other tests now, and so far (after several minutes) no errors have been reported. (I don't know how long the tests take to run, and I'm not sure than I will run this all the way to the end, but feel free to do so.)

You should probably add JDK 15 to any continuous integration setup you might be using, since the JRE is significantly faster than previous versions for some workloads -- so there will be a lot of motivation for users to upgrade to JDK 15.

Note that in recent JDKs, JavaFX is not included, so there are compilation errors for `smile/scala/src/main/scala/smile/plot/vega/WindowFX.scala` . Maybe you can make that an optional library, or use reflection instead?

I won't close the bug since I wanted to make sure you saw the JavaFX comment, but feel free to close this once you have read this.
