### ISSUE TITLE
Implementation of predict in KModes

### ISSUE THREAD

**Issue by PavelZeger** [haifengl/smile#616]
Hello.
I would like to refactor a python code using this library but didn't find the proper way to rewrite this part:
```python
from kmodes.kmodes import KModes
km = KModes(n_clusters=20, max_iter = 20, init='Huang', n_init=4, verbose=1, n_jobs=-1)
clusters = km.fit_predict(df)
```
Is it possible to do it with this library?

When I tried to check with the simple Scala array:
```scala
import smile.clustering.kmodes
val data = Array(Array(0,0,1),Array(1,0,0))
val km = kmodes(data, 4, 4, 4)
```
 I got the following error:
```log
java.lang.IllegalArgumentException: Only one class.
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Only one class.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.Nodes.collect(Nodes.java:325)
	at java.util.stream.ReferencePipeline.evaluateToNode(ReferencePipeline.java:109)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:541)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at smile.clustering.KModes.fit(KModes.java:89)
	at smile.clustering.package$.$anonfun$kmodes$2(package.scala:155)
	at smile.clustering.PartitionClustering.lambda$run$1(PartitionClustering.java:177)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at java.util.stream.ReferencePipeline.min(ReferencePipeline.java:520)
	at smile.clustering.PartitionClustering.run(PartitionClustering.java:178)
	at smile.clustering.package$.$anonfun$kmodes$1(package.scala:155)
	at smile.util.package$time$.apply(package.scala:57)
	at smile.clustering.package$.kmodes(package.scala:155)
	at com.undertone.KModesAppTest.$anonfun$new$1(KModesAppTest.scala:83)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.invokeWithFixture$1(FunSuiteLike.scala:184)
	at org.scalatest.FunSuiteLike.$anonfun$runTest$1(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FunSuiteLike.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike.runTest$(FunSuiteLike.scala:178)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$runTests$1(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FunSuiteLike.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike.runTests$(FunSuiteLike.scala:228)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike.$anonfun$run$1(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FunSuiteLike.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike.run$(FunSuiteLike.scala:232)
	at com.undertone.KModesAppTest.org$scalatest$BeforeAndAfterAll$$super$run(KModesAppTest.scala:15)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at com.undertone.KModesAppTest.run(KModesAppTest.scala:15)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1346)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1340)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:41)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
Caused by: java.lang.IllegalArgumentException: Only one class.
	at smile.classification.ClassLabels.fit(ClassLabels.java:91)
	at smile.clustering.KModes.lambda$fit$0(KModes.java:88)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.Nodes$SizedCollectorTask.compute(Nodes.java:1878)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by haifengl** [comment]
try more data

**Comment by PavelZeger** [comment]
I tried also with 50,000 rows test data set I have and got the same error.

**Comment by haifengl** [comment]
Are you using Java 8?

**Comment by PavelZeger** [comment]
Yes. Java 8

**Comment by haifengl** [comment]
Can you share the data so that I reproduce the problem? Thanks

**Comment by PavelZeger** [comment]
You can find it here: https://gofile.io/d/a8SmHJ
I created from this dataset an Array[Array[Int]]

**Comment by haifengl** [comment]
Your data has constant columns, which cause the problem. I made some change to handle it. Try the master branch.

**Comment by PavelZeger** [comment]
Thank you! I'll try

**Comment by PavelZeger** [comment]
I'm still getting the same error with the sampled dataset I sent you:

**Comment by PavelZeger** [comment]
I'm still getting the same error with the sampled dataset I sent you:
```
import utils.SparkSessionSetupTest
import org.apache.spark.sql.functions.col
import org.scalatest.{FunSuite, Matchers}
import smile.clustering.kmodes

class KModesAppTest extends FunSuite with Matchers with SparkSessionSetupTest {

  test("execute") {

    val datasetName: String = "df_2_for_kmodes"
    val dataset = sparkSession
          .read
          .option("header", "true")
          .option("sep", ",")
          .option("encoding", "UTF-8")
          .option("inferSchema", "true")
          .option("ignoreLeadingWhiteSpace", "true")
          .option("ignoreTrailingWhiteSpace", "true")
          .option("mode", "DROPMALFORMED")
          .csv(s"src/test/resources/$datasetName.csv")
          .drop(col("request_id"))

    dataset.printSchema()
    dataset.show()

    val numberOfClusters: Int = 20
    val maxIterations: Int = 20
    val numberOfInitializations: Int = 4

    val parsedDataset = Array(dataset.collect().map(_.getInt(0)))
    val km = kmodes(parsedDataset, numberOfClusters, maxIterations, numberOfInitializations)

  }

}
```

**Comment by haifengl** [comment]
You must miss something as the new version wouldn't throw that exception. For example,

- Make sure you use the right version in your build system. The master version is 2.6.0. 
- After build, publish it locally `publishLocal` or `publishM2` depending on your build system.
- You better remove the column `request_hour_0` too. It doesn't look like a categorical variable to me.

**Comment by haifengl** [comment]
You sure about this `parsedDataset = Array(dataset.collect().map(_.getInt(0)))`? Have you checked the results?
