### ISSUE TITLE
Dependency issue to make SpectralClustering working

### ISSUE THREAD

**Issue by genmeblog** [haifengl/smile#619]
Can't get proper dependencies to have all clustering algorithms working. Any idea?

**Describe the bug**

Version 1:

```clojure
                 [com.github.haifengl/smile-interpolation "2.5.3"]
                 [com.github.haifengl/smile-core "2.5.3"]
                 [com.github.haifengl/smile-mkl "2.5.3"]
```

When trying to use SpectralClustering I'm getting the error:

```
Execution error (NoClassDefFoundError) at smile.math.matrix.ARPACK/syev (ARPACK.java:161).
org/bytedeco/arpackng/global/arpack
```

```
               ARPACK.java:  161  smile.math.matrix.ARPACK/syev
               ARPACK.java:  113  smile.math.matrix.ARPACK/syev
   SpectralClustering.java:  108  smile.clustering.SpectralClustering/fit
   SpectralClustering.java:  163  smile.clustering.SpectralClustering/fit
   SpectralClustering.java:  128  smile.clustering.SpectralClustering/fit
```

Version 2:

Adding arpack and openblas:

```clojure
                 [com.github.haifengl/smile-interpolation "2.5.3"]
                 [com.github.haifengl/smile-core "2.5.3"]
                 [com.github.haifengl/smile-mkl "2.5.3"]
                 [org.bytedeco/arpack-ng "3.7.0-1.5.4"]
                 [org.bytedeco/openblas "0.3.10-1.5.4"]
                 [org.bytedeco/javacpp "1.5.4"]
```

After calling SpectralClustering fitting:

```
Execution error (UnsatisfiedLinkError) at java.lang.ClassLoader/loadLibrary (ClassLoader.java:2680).
no openblas_nolapack in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
```

Version 3:

Excluding MKL

```clojure
                 [com.github.haifengl/smile-interpolation "2.5.3"]
                 [com.github.haifengl/smile-core "2.5.3"]
                 [org.bytedeco/arpack-ng "3.7.0-1.5.4"]
                 [org.bytedeco/openblas "0.3.10-1.5.4"]
                 [org.bytedeco/javacpp "1.5.4"]
```

Calling SpectralClustering:

```
Warning: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
Execution error (UnsatisfiedLinkError) at java.lang.ClassLoader/loadLibrary (ClassLoader.java:2680).
no openblas_nolapack in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
Could not initialize class org.bytedeco.openblas.global.openblas_nolapack
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.openblas.global.openblas_nolapack
```

When trying to call DeterministingAnnealing:

```
23:56:14.807 [nREPL-session-035cd925-657e-48b1-b8d7-8d60b87b940a] DEBUG smile.math.blas.BLAS - Failed to create MKL instance: 
java.lang.ClassNotFoundException: smile.math.blas.mkl.MKL
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:340)
	at smile.math.blas.BLAS.MKL(BLAS.java:47)
	at smile.math.blas.BLAS.getInstance(BLAS.java:38)
	at smile.math.blas.BLAS.<clinit>(BLAS.java:34)
	at smile.math.matrix.Matrix.mv(Matrix.java:1250)
	at smile.math.matrix.Matrix.mv(Matrix.java:1256)
	at smile.math.matrix.DMatrix.mv(DMatrix.java:115)
	at smile.math.matrix.PowerIteration.ax(PowerIteration.java:115)
	at smile.math.matrix.PowerIteration.eigen(PowerIteration.java:88)
	at smile.clustering.DeterministicAnnealing.fit(DeterministicAnnealing.java:106)
```

**Additional context**
```
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)
```
- Smile 2.5.3
- WSL 2.0 (Ubuntu 20.04.1 LTS) on Windows 10
- Calling from Clojure 1.10.1

**Comment by haifengl** [comment]
Version 3 is the right setting. But JavaCPP fails to load the native library somehow. It is likely an issue with WSL. Can you try it with plain windows (or linux)?

**Comment by genmeblog** [comment]
WSL2 is actually Ubuntu on VM. Should behave as regular Ubuntu I suppose. I'll try to setup Windows env.

Anyway: if version 3 is proper one, how to make DeterministicAnnealing (which requires MKL) work then?

**Comment by genmeblog** [comment]
Ok, I understand it should fallback to OpenBLAS when MKL is not found, right?

**Comment by haifengl** [comment]
yes. it is a debug message, not an error.

**Comment by genmeblog** [comment]
Before I try on different env, I just leave one finding here. There was similar issue with deeplearning4j (connected with spring boot which looks unrelated here)

https://github.com/eclipse/deeplearning4j/issues/6132

**Comment by genmeblog** [comment]
Also, just to mention: version 2.5.0 works perfectly.

**Comment by haifengl** [comment]
Looks like a clojure limitation: https://ask.clojure.org/index.php/7861/native-library-support-for-tools-deps

**Comment by genmeblog** [comment]
It's about `tools.deps`. I use `leiningen` which works for Chris. Also It works for me with Smile 2.5.0.

**Comment by haifengl** [comment]
Smile 2.5.0 transparently includes OpenBlas dependency. But we avoid it from 2.5.1 as not everyone needs it.

**Comment by genmeblog** [comment]
2.5.3 on Linux (Ubuntu) still raises the same error. I prepared minimal Clojure project based on Leiningen, here:

https://github.com/genmeblog/smiletest

It just calls `fit` on two classes:

```clojure
(ns smiletest.core
  (:import [smile.clustering DeterministicAnnealing SpectralClustering]))

(def data (into-array (map (fn [id] (double-array (repeatedly 1000 #(+ id (* (rand) (rand)))))) (range 1 50 7))))
(def deterministic-annealing (DeterministicAnnealing/fit data 7))
(def spectral-clustering (SpectralClustering/fit data 4 10))
```

Tested on pure Linux (Ubuntu):

```
 java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

Here is the example session from the scratch (on my env, ubuntu on wsl2):

```sh
~/src$ git clone git@github.com:genmeblog/smiletest.git
Cloning into 'smiletest'...
[...]
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 14 (delta 0), reused 14 (delta 0), pack-reused 0
Receiving objects: 100% (14/14), 7.24 KiB | 2.41 MiB/s, done.
~/src$ cd smiletest/
~/src/smiletest$ lein repl
[...]
nREPL server started on port 45163 on host 127.0.0.1 - nrepl://127.0.0.1:45163
REPL-y 0.4.4, nREPL 0.7.0
Clojure 1.10.1
OpenJDK 64-Bit Server VM 14.0.2+12-Ubuntu-120.04
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require '[smiletest.core])
21:55:18.186 [nREPL-session-134c0f3d-6010-4d9a-9449-83e8c21176ec] INFO  smile.math.blas.BLAS - smile-mkl module is available. {  }
21:55:19.567 [nREPL-session-134c0f3d-6010-4d9a-9449-83e8c21176ec] INFO  smile.math.matrix.PowerIteration - Largest eigenvalue after   3 power iterations: 228626.8445 {  }
21:55:19.594 [nREPL-session-134c0f3d-6010-4d9a-9449-83e8c21176ec] INFO  s.clustering.DeterministicAnnealing - Entropy after   1 iterations at temperature 457253.6991 and k = 1: 4.8519 (soft distortion = 1372034.4800) {  }
[...]
21:55:20.259 [nREPL-session-134c0f3d-6010-4d9a-9449-83e8c21176ec] INFO  s.clustering.DeterministicAnnealing - Entropy after  53 iterations at temperature 422080.3376 and k = 7: 17.0620 (soft distortion = 1372009.6690) {  }
Execution error (UnsatisfiedLinkError) at java.lang.ClassLoader/loadLibrary (ClassLoader.java:2680).
no openblas_nolapack in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]

user=>
```

**Comment by haifengl** [comment]
It should a pure clojure issue. A work around is to build smile by yourself. In smile/math/build.sbt, remove "provided" from JavaCpp related dependency.

**Comment by genmeblog** [comment]
Ok. Starting to believe that Leiningen has some problems with resolving dependencies on some cases... Will be investigating.

**Comment by genmeblog** [comment]
Maybe one more question: why spectral clustering requires openblas when MKL is available?

**Comment by genmeblog** [comment]
Thanks to @cnuernber here is the valid list of dependencies for Clojure:

```clojure
                 [com.github.haifengl/smile-core "2.5.3"]
                 [com.github.haifengl/smile-mkl "2.5.3"]
                 [org.bytedeco/arpack-ng "3.7.0-1.5.4"]
                 [org.bytedeco/openblas-platform "0.3.10-1.5.4"]
                 [org.bytedeco/arpack-ng          "3.7.0-1.5.4"]
                 [org.bytedeco/arpack-ng-platform "3.7.0-1.5.4"]
                 [org.bytedeco/openblas "0.3.10-1.5.4"]
                 [org.bytedeco/javacpp "1.5.4"]
```

**Comment by haifengl** [comment]
Spectral clustering uses arpack, which binds to openblas by default. It is possible for it to use mkl with some configuration. Check javacpp site for details.

**Comment by genmeblog** [comment]
Ok, thanks for explaining... Closing issue then.
