### ISSUE TITLE
MultivariateGaussianMixture: The matrix is not square

### ISSUE THREAD

**Issue by PooyaRah** [haifengl/smile#643]
Hi

I used `MultivariateGaussianMixture.fit(32, mfcc, true)`  with data `double[2083][39] mfcc;`  and have error:

`Exception in thread "main" java.lang.IllegalArgumentException: The matrix is not square: 39 x 1
  at smile.math.matrix.Matrix.uplo(Matrix.java:486)
  at smile.stat.distribution.MultivariateGaussianDistribution.init(MultivariateGaussianDistribution.java:169)
  at smile.stat.distribution.MultivariateGaussianDistribution.<init>(MultivariateGaussianDistribution.java:123)
  at smile.stat.distribution.MultivariateGaussianDistribution.M(MultivariateGaussianDistribution.java:356)
  at smile.stat.distribution.MultivariateExponentialFamilyMixture.fit(MultivariateExponentialFamilyMixture.java:139)
  at smile.stat.distribution.MultivariateExponentialFamilyMixture.fit(MultivariateExponentialFamilyMixture.java:71)
  at smile.stat.distribution.MultivariateGaussianMixture.fit(MultivariateGaussianMixture.java:139)
  at com.pghavin.Speech.Main.main(Main.java:58)`

what should I do?

**Comment by haifengl** [comment]
Which version are you using?

**Comment by haifengl** [comment]
I find the root cause and push a fix to the master branch. Please have a try. Thanks!
