### ISSUE TITLE
Giving LongStream of seeds to RandomForest leads sometimes to a weird IndexOutOfBoundsException

### ISSUE THREAD

**Issue by pletinckxc** [haifengl/smile#658]
**Describe the bug**
When trying to train a `RandomForest` with a `LongStream` of seeds my code encounters an IndexOutOfBoundsException from time to time.

**Expected behavior**
The model should return a well-fitted `RandomForest` object, as it does in the normal case, and always with the same trees from run to run.

**Actual behavior**
The returned object is always the same from run to run but sometimes the exception raises. Here is the stracktrace : 
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
	at java.base/java.util.stream.Nodes.collect(Nodes.java:333)
	at java.base/java.util.stream.ReferencePipeline.evaluateToNode(ReferencePipeline.java:109)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at smile.regression.RandomForest.fit(RandomForest.java:288)
	at Scratch.main(scratch.java:59)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 624 out of bounds for length 624
	at smile.math.random.MersenneTwister.setSeed(MersenneTwister.java:93)
	at smile.math.random.MersenneTwister.setSeed(MersenneTwister.java:87)
	at smile.math.Random.setSeed(Random.java:56)
	at smile.math.MathEx.setSeed(MathEx.java:499)
	at smile.regression.RandomForest.lambda$fit$0(RandomForest.java:234)
	at java.base/java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177)
	at java.base/java.util.Spliterators$LongArraySpliterator.forEachRemaining(Spliterators.java:1115)
	at java.base/java.util.Spliterator$OfLong.forEachRemaining(Spliterator.java:763)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.Nodes$SizedCollectorTask.compute(Nodes.java:1886)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

Process finished with exit code 1
```

**Code snippet**
```
import smile.data.DataFrame;
import smile.data.Tuple;
import smile.data.formula.Formula;
import smile.data.measure.NominalScale;
import smile.data.type.DataType;
import smile.data.type.StructField;
import smile.data.type.StructType;
import smile.regression.RandomForest;
import smile.regression.RegressionTree;

import java.util.*;
import java.util.stream.LongStream;

class Scratch {
    public static void main(String[] args) {
        String[] predictors = new String[3];
        predictors[0] = "love";
        predictors[1] = "hormone";
        predictors[2] = "level";
        Formula formula = Formula.of("objective", predictors);

        ArrayList<String> levels = new ArrayList<>();
        levels.add("in love");
        levels.add("not in love");
        levels.add("fool");

        ArrayList<StructField> structFields = new ArrayList<>();
        structFields.add(new StructField("love", DataType.of(Integer.class), new NominalScale(levels)));
        structFields.add(new StructField("hormone", DataType.of(Double.class)));
        structFields.add(new StructField("objective", DataType.of(Double.class)));
        structFields.add(new StructField("level", DataType.of(Integer.class)));
        StructType structType = new StructType(structFields);

        ArrayList<Tuple> data = new ArrayList<>();
        Object[] values = new Object[4];
        values[structType.fieldIndex("love")] = structType.field("love").valueOf("in love");
        values[structType.fieldIndex("hormone")] = 2.5;
        values[structType.fieldIndex("objective")] = 10.0;
        values[structType.fieldIndex("level")] = 5;
        Tuple one = Tuple.of(values, structType);
        data.add(one);
        Object[] values2 = new Object[4];
        values2[structType.fieldIndex("love")] = structType.field("love").valueOf("not in love");
        values2[structType.fieldIndex("hormone")] = 0.2;
        values2[structType.fieldIndex("objective")] = 0.0;
        values2[structType.fieldIndex("level")] = 1;
        Tuple two = Tuple.of(values2, structType);
        data.add(two);

        DataFrame dataFrame = DataFrame.of(data);

        LongStream seeds = LongStream.range(42, 52);
        RandomForest rf = RandomForest.fit(formula, dataFrame, 10, structType.length() - 1, Integer.MAX_VALUE, Integer.MAX_VALUE, 1, 1.0, seeds);
        Object[] toPredict = new Object[4];
        toPredict[structType.fieldIndex("love")] = (int) (byte) structType.field("love").valueOf("not in love");
        toPredict[structType.fieldIndex("hormone")] = 1.0;
        toPredict[structType.fieldIndex("objective")] = 0.0;
        toPredict[structType.fieldIndex("level")] = 2;
        Tuple three = Tuple.of(toPredict, structType);
        System.out.println("Random forest prediction : " + rf.predict(three));
        System.out.println("=================================================================================");
        RegressionTree[] trees = rf.trees();
        int ind = 0;
        for (RegressionTree tree : trees) {
            //System.out.println(tree.toString());
            System.out.println("Tree prediction for " + ind + " : " + tree.predict(three));
            System.out.println("=================================================================================");
            ind++;
        }
    }
}
```

**Additional context**
- I'm using Intellij with OpenJDK, Java version 11.0.7 with SDK language level 11.
- I'm using Smile version 2.6.0 downloaded from maven.
- I'm using Windows.
- The project also includes the `org.apache.commons:commons-math3:3.6.1` library and the `slf4j-nop-1.7.30.jar` file.

**Comment by haifengl** [comment]
Your seed stream has only 10 values. You should supply the stream with enough values (at least same as the number of trees). A couple of suggestions:

- You should not supply the seeds at all. It is used to generate reproducible random forest (useful for test).
- If you have to supply seeds, provide good ones. Yours are not good from information theory point of view.

**Comment by pletinckxc** [comment]
You suggest to have more seeds than the number of trees ? Because in my code snippet (which is a toy example) I only generated a RandomForest with 10 trees so 10 different seeds should be enough for the code to work right ?

For now I need to supply the seeds because I must have reproducible results. 
I don't know much about information theory. Could you tell me how I could improve the code ? Also I noticed that seeds below one are not accepted in RandomForest. Is there a reason for that ?

**Comment by haifengl** [comment]
What's smile version you use?

**Comment by pletinckxc** [comment]
2.6.0
