### ISSUE TITLE
Failed to run DENCLUE on multi-core java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by kienlo** [haifengl/smile#677]
When I create a new instance DENCLUE by input data greater than 1000 items. And it always throws an error
Failed to run DENCLUE on multi-core
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at smile.util.MulticoreExecutor.run(MulticoreExecutor.java:107)
	at smile.clustering.DENCLUE.<init>(DENCLUE.java:140)

I see your algorithm and see that you create a lot of threads to run it. But some thread no data.
How can I resolve it instead upgrade the library?
I using version 1.3.1

**Comment by haifengl** [comment]
1.3.1 is very old. Why don't you try latest version 2.6 or master branch?
