### ISSUE TITLE
GP Regression HPO IndexOutOfBoundsException

### ISSUE THREAD

**Issue by DirkToewe** [haifengl/smile#693]
The following code fails with an IndexOutOfBoundsException:
```java
double[][] X = {{3.0}, {4.0}, {4.0}, {4.0}, {9.0}, {10.0}, {10.0}, {10.0}, {10.0}, {10.0}};
double[]   y = {9.0, 12.0, 11.0, 9.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0};

var gps = GaussianProcessRegression.fit(
  X,y, new GaussianKernel(3),
  /*noise=*/1e-5, /*normalize=*/false, /*tol=*/1e-5, /*masIter=*/1024
);
```
Stack trace:
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: 16
	at java.base/java.nio.HeapDoubleBuffer.put(HeapDoubleBuffer.java:218)
	at smile.math.matrix.Matrix.set(Matrix.java:684)
	at smile.math.BFGS.minimize(BFGS.java:719)
	at smile.regression.GaussianProcessRegression.fit(GaussianProcessRegression.java:368)
	at com.github.jaaa.GPRExample.main(GPRExample.java:11)
```
If I am not mistaken, the resizing of `W` in L-BFGS-B optimizer seems to be tied to the wrong condition (BFGS.java L702).
```java
if (iter <= m)
```
should be
```java
if( W.ncols() < 2*h )
```
right?

**Additional context**
- JDK: adopt-openjdk-16
- Smile: 2.6.0
- org.bytedeco:openblas:0.3.17-1.5.6:linux-x86_64
- org.bytedeco:arpack-ng:3.8.0-1.5.6:linux-x86_64

**Comment by haifengl** [comment]
It is L-BFGS. The first m steps need special handling. Can you try a real multi-dimensional data?

**Comment by DirkToewe** [comment]
> Can you try a real multi-dimensional data?

In my case, the real data is in fact univariate (noisy performance curves). But I can try to find a multivariate example as well.

> The first m steps need special handling.

It should be the first m *updates* not the first m *steps*, right? I do not understand the code in its entirety, but it seems like sometime updates are rejected if they are not guaranteed to be positive definite or not positive definite "enough", see [BFGS.java#L687](https://github.com/haifengl/smile/blob/master/math/src/main/java/smile/math/BFGS.java#L687). That means there may be more steps than updates, if I am not mistaken.

**Comment by ZeliangSu** [comment]
I'm still getting OOB issues, using the above two examples
