### ISSUE TITLE
Fail to train a regression model

### ISSUE THREAD

**Issue by davidzxc574** [haifengl/smile#697]
**Describe the bug**
I got this error message when trying to run gbm, cart, randomForest, ols regression.

```
java.lang.NoClassDefFoundError: smile/util/package$
  at smile.util.package$time$.apply(package.scala:64)
  at smile.regression.package$.cart(package.scala:249)
...
```
**Code snippet**
```
import smile.regression.{gbm,randomForest,cart,ols}
import smile.data.DataFrame
import smile.data.formula._
import smile.util._

val arrX=lisSamp.map(x=>Array(x._4.toDouble,x._5.toDouble,x._6.toDouble,x._7.toDouble,x._8.toDouble)).toArray
val arrY=lisSamp.map(x=>Array(x._3)).toArray
val sdfX=DataFrame.of(arrX)
val sdfY=DataFrame.of(arrY,"Y")
val sdfFull=sdfX.merge(sdfY)

//train model
val forForm:Formula="Y"~"V1"+"V2"+"V3"
randomForest(forForm,sdfFull,50,3,10,50,100,1)
cart(forForm,sdfFull,10,100,5)
gbm(forForm, sdfFull)
ols(forForm, sdfFull,"qr")
```

**Input data**
The data frame looks like this
```
scala> sdfFull
res40: smile.data.DataFrame =
[V1: double, V2: double, V3: double, V4: double, V5: double, Y: double]
+---+---+---+---+---+---+
| V1| V2| V3| V4| V5|  Y|
+---+---+---+---+---+---+
|  2|  0| 21|  3| 65|  1|
|  2|  0| 21|  3| 70|  1|
|  2|  0| 21|  3| 75|  1|
|  2|  0| 21|  3| 80|  1|
|  2|  0| 21|  3| 85|  1|
|  2|  0| 21|  3| 90|  1|
|  2|  0| 21|  3| 95|  1|
|  2|  0| 21|  3|100|  1|
|  2|  0| 21|  3|105|  1|
|  2|  0| 21|  3|110|  1|
+---+---+---+---+---+---+
156 more rows...
```

**Additional context**
I have scala 2.11 and JDK1.8, running smile 2.4.0 on CDH.
When importing smile.util._ it gave error below, but it went through when importing the 2nd time.
```
error: missing or invalid dependency detected while loading class file 'package.class'.
Could not access term typesafe in package com,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'package.class' was compiled against an incompatible version of com.
error: missing or invalid dependency detected while loading class file 'package.class'.
Could not access type LazyLogging in value com.scalalogging,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
A full rebuild may help if 'package.class' was compiled against an incompatible version of com.scalalogging.

```

**Comment by davidzxc574** [comment]
> 
> 
> Your path doesn't look right to me. And depending on your spark version, you may need 2.12 version.

Thanks for the reply. The path worked as I could import smile packages. The reason that could cause the issue is that I am missing some smile package/class as the error message tells. I use Spark 2.2.0 with scala 2.11 but why there is a relationship between spark and smile? You were saying I need scala 2.12, ? I use spark to fetch data from hive tables only. Then I process data with vectors and lists.
