### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib

### ISSUE THREAD

**Issue by manju22412** [haifengl/smile#743]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
at java.base/java.lang.System.loadLibrary(System.java:1989)
at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
at org.bytedeco.openblas.global.openblas_nolapack.(openblas_nolapack.java:12)
at java.base/java.lang.Class.forName0(Native Method)
at java.base/java.lang.Class.forName(Class.java:467)
at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
at org.bytedeco.openblas.global.openblas.(openblas.java:13)
at smile.math.blas.openblas.OpenBLAS.gemv(OpenBLAS.java:106)
at smile.math.matrix.Matrix.mv(Matrix.java:1491)
at smile.math.matrix.IMatrix.mv(IMatrix.java:271)
at smile.neighbor.lsh.Hash.hash(Hash.java:146)
at smile.neighbor.lsh.Hash.add(Hash.java:164)
at smile.neighbor.LSH.put(LSH.java:209)
at smile.neighbor.LSH.(LSH.java:116)
at temp.LSHTest.(LSHTest.java:25)
at temp.ClientCode.main(ClientCode.java:5)
Caused by: java.lang.UnsatisfiedLinkError: Could not find jniopenblas_nolapack in class, module, and library paths.
at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1799)
... 19 more

**Comment by manju22412** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:12)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.openblas.global.openblas.<clinit>(openblas.java:13)
	at smile.math.blas.openblas.OpenBLAS.gemv(OpenBLAS.java:106)
	at smile.math.matrix.Matrix.mv(Matrix.java:1491)
	at smile.math.matrix.IMatrix.mv(IMatrix.java:271)
	at smile.neighbor.lsh.Hash.hash(Hash.java:146)
	at smile.neighbor.lsh.Hash.add(Hash.java:164)
	at smile.neighbor.LSH.put(LSH.java:209)
	at smile.neighbor.LSH.<init>(LSH.java:116)
	at temp.LSHTest.<init>(LSHTest.java:25)
	at temp.ClientCode.main(ClientCode.java:5)
Caused by: java.lang.UnsatisfiedLinkError: Could not find jniopenblas_nolapack in class, module, and library paths.
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1799)
	... 19 more

**Comment by lihaife** [comment]
You should have OpenBlas installed.

**Comment by manju22412** [comment]
@lihaife thank u for reply 
but can u say how to install that OpenBlas

**Comment by lihaife** [comment]
What OS do you use?

**Comment by manju22412** [comment]
@lihaife ubuntu

**Comment by saudet** [comment]
Please set the "org.bytedeco.javacpp.logger.debug" system property to "true" to get more information on the console.

**Comment by manju22412** [comment]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/manjunad-17777/Documents/My_project_ML-Algarithms/ML_Algorithms_FTWVCS/lib/slf4j-jdk14-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/manjunad-17777/Documents/My_project_ML-Algarithms/ML_Algorithms_NLP/lib/slf4j-jdk14-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.javacpp.Loader
Debug: Loading library jnijavacpp
Debug: Failed to load for jnijavacpp: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Could not load Loader: java.lang.UnsatisfiedLinkError: no jnijavacpp in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
Debug: Loading class org.bytedeco.javacpp.presets.javacpp
Debug: Loading class org.bytedeco.openblas.global.openblas_nolapack
Debug: Loading library gcc_s
Debug: Failed to load for gcc_s@.1: java.lang.UnsatisfiedLinkError: no gcc_s in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library quadmath
Debug: Failed to load for quadmath@.0: java.lang.UnsatisfiedLinkError: no quadmath in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library gfortran
Debug: Failed to load for gfortran@.5: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library gfortran
Debug: Failed to load for gfortran@.4: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library gfortran
Debug: Failed to load for gfortran@.3: java.lang.UnsatisfiedLinkError: no gfortran in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library openblas
Debug: Failed to load for openblas@.0#openblas_nolapack@.0: java.lang.UnsatisfiedLinkError: no openblas in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library openblas_nolapack
Debug: Failed to load for openblas_nolapack@.0: java.lang.UnsatisfiedLinkError: no openblas_nolapack in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Debug: Loading library jniopenblas_nolapack
Debug: Failed to load for jniopenblas_nolapack: java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopenblas_nolapack in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.openblas.global.openblas_nolapack.<clinit>(openblas_nolapack.java:12)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1289)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.openblas.global.openblas.<clinit>(openblas.java:13)
	at smile.math.blas.openblas.OpenBLAS.gemv(OpenBLAS.java:106)
	at smile.math.matrix.Matrix.mv(Matrix.java:1491)
	at smile.math.matrix.IMatrix.mv(IMatrix.java:261)
	at smile.neighbor.lsh.MultiProbeHash.mphash(MultiProbeHash.java:66)
	at smile.neighbor.lsh.MultiProbeHash.add(MultiProbeHash.java:89)
	at smile.neighbor.LSH.put(LSH.java:209)
	at com.zlabs.ml.algo.nearestneighborsearch.NearestNeighborSearch.<init>(NearestNeighborSearch.java:26)
	at com.zlabs.ml.algo.nearestneighborsearch.NearestNeighborSearchClientCode.main(NearestNeighborSearchClientCode.java:24)
Caused by: java.lang.UnsatisfiedLinkError: Could not find jniopenblas_nolapack in class, module, and library paths.
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1799)
	... 18 more


IT SHOWS LIKE THIS NOW...

**Comment by saudet** [comment]
That means openblas-platform and all its dependencies are missing from the class path. Make sure they are all in your class path by using a dependency like this: https://github.com/bytedeco/javacpp-presets/tree/master/openblas#the-pomxml-build-file

**Comment by manju22412** [comment]
i imported openblas, javacpp, and openblas-platform, javacpp-platform tooo
but still it showing like that..

**Comment by saudet** [comment]
You need the *dependencies* of openblas-platform, not openblas-platform, that's just an empty JAR. You'll need to figure out why your build tool doesn't want to include the dependencies of openblas-platform, or your could include them yourself manually.

**Comment by lihaife** [comment]
A workaround is to add smile-mkl package to your project. It will include all necessary libraries.

**Comment by manju22412** [comment]
@lihaife after using mkl, it showing like this..

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnimkl_rt in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1832)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1423)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1234)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1210)
	at org.bytedeco.mkl.global.mkl_rt.<clinit>(mkl_rt.java:12)
	at smile.math.blas.mkl.MKL.gemv(MKL.java:106)
	at smile.math.matrix.Matrix.mv(Matrix.java:1491)
	at smile.math.matrix.IMatrix.mv(IMatrix.java:261)
	at smile.neighbor.lsh.MultiProbeHash.mphash(MultiProbeHash.java:66)
	at smile.neighbor.lsh.MultiProbeHash.add(MultiProbeHash.java:89)
	at smile.neighbor.LSH.put(LSH.java:209)
	at com.zlabs.ml.algo.nearestneighborsearch.NearestNeighborSearch.<init>(NearestNeighborSearch.java:26)
	at com.zlabs.ml.algo.nearestneighborsearch.NearestNeighborSearchClientCode.main(NearestNeighborSearchClientCode.java:24)
Caused by: java.lang.UnsatisfiedLinkError: Could not find jnimkl_rt in class, module, and library paths.
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1799)
	... 12 more

**Comment by manju22412** [comment]
> You need the _dependencies_ of openblas-platform, not openblas-platform, that's just an empty JAR. You'll need to figure out why your build tool doesn't want to include the dependencies of openblas-platform, or your could include them yourself manually.

@saudet, i included all dependencies if not it might have shown error like noclassfound or nomethodfound right, but it didn't shown anything 
gives unsatisfiedlink error..

**Comment by lihaife** [comment]
What JVM do you use?
