### ISSUE TITLE
DataFrame.factorize throws a NullPointerException

### ISSUE THREAD

**Issue by vmunier** [haifengl/smile#789]
**Describe the bug**
`DataFrame.factorize` throws a NullPointerException when one of the values in a StringVector is null.

**Expected behavior**
`DataFrame.factorize` should handle null values.

**Actual behavior**
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Comparable.compareTo(Object)" because "c1" is null
 	at java.base/java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:52)
 	at java.base/java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47)
 	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
 	at java.base/java.util.TimSort.sort(TimSort.java:220)
 	at java.base/java.util.Arrays.sort(Arrays.java:1308)
 	at java.base/java.util.ArrayList.sort(ArrayList.java:1804)
 	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:392)
 	at java.base/java.util.stream.DistinctOps$1$2.end(DistinctOps.java:168)
 	at java.base/java.util.stream.Sink$ChainedInt.end(Sink.java:293)
 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
 	at smile.data.DataFrame.lambda$factorize$6(DataFrame.java:992)
 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
 	at smile.data.DataFrame.factorize(DataFrame.java:1003)
```

**Code snippet**
```
import smile.data.DataFrame;
import smile.data.vector.StringVector;

public class Main {
    public static void main(String[] args) {
        String[] categories = {"A", "B", "C", null};
        DataFrame df = DataFrame.of(StringVector.of("categories", categories));
        df.factorize();
    }
}
```

**Input data**

**Additional context**
Looks like it's failing when sorting the collection https://github.com/haifengl/smile/blob/v3.1.1/base/src/main/java/smile/data/DataFrame.java#L992

**Comment by haifengl** [comment]
As a work around, you may replace null with empty string "".

**Comment by vmunier** [comment]
Thanks for the workaround. The thing is I would like to keep null values to be able to use the SimpleImputer and imputes nominal columns with mode.

**Comment by haifengl** [comment]
Nominal variable doesn't take null values as internally they are integers. For your use cases, I suggest call SimpleImputer before factorize.
